MGS-7375 [#nxp] fix build error when kasan enable
commit 9df13ee761aefabff2494fbbce56b945190d31e4 from
https://github.com/nxp-imx/linux-imx.git

fix below build error when CONFIG_KASAN=y

    inlined from ‘int_id_overrides_write’ at drivers/gpu/arm/midgard/mali_kbase_pbha_debugfs.c:96:6:
./include/linux/kasan-checks.h:38:27: error: ‘raw_str’ may be used uninitialized [-Werror=maybe-uninitialized]
   38 | #define kasan_check_write __kasan_check_write
./include/linux/instrumented.h:129:9: note: in expansion of macro ‘kasan_check_write’
  129 |         kasan_check_write(to, n);
      |         ^~~~~~~~~~~~~~~~~

Signed-off-by: Jiyu Yang <jiyu.yang@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>