MA-22143-2 phy: phy-fsl-imx9-dphy-rx: Fix typo in dw_dphy_rx_of_match
commit a43bb5183996c50ae3f55e77eec554287a43abc5 from
https://github.com/nxp-imx/linux-imx.git

Fix below build error when building it as a module:
  drivers/phy/freescale/phy-fsl-imx9-dphy-rx.c:463:25: error: use of
undeclared identifier 'dw_dphy_rx_of_match';did you mean 'dw_dphy_of_match'
MODULE_DEVICE_TABLE(of, dw_dphy_rx_of_match);

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: G.N. Zhou <guoniu.zhou@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>