MA-22385 neutron: Fix variable initialization causing build error
commit b9d21c05dcd6824edb6115ff990d22a926a40048 from
https://github.com/nxp-imx/linux-imx.git

error log:
drivers/staging/neutron/neutron_inference.c:348:3: error: expected expression
struct neutron_uapi_result_status uapi;

Change-Id: I8e33bd706f65660532e3ec650315dff369bcf055
Signed-off-by: Zhipeng Wang <zhipeng.wang_1@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>