LF-12051: firmware: imx: fix compile error
commit 4a114c55368761cd66c90b5b3eacecb1d2b7e6a6 from
https://github.com/nxp-imx/linux-imx.git

./include/linux/firmware/imx/sm.h:29:1: error: expected identifier or ‘(’ before ‘{’ token
   29 | {
      | ^
./include/linux/firmware/imx/sm.h:28:19: warning: ‘scmi_imx_misc_ctrl_set’ used but never defined
   28 | static inline int scmi_imx_misc_ctrl_set(u32 id, u32 val);

Fixes: d482cb8ff959 ("LF-10712-2 firmware: imx: add i.MX SM MISC driver")
Signed-off-by: Shengjiu Wang <shengjiu.wang@nxp.com>
Reviewed-by: Peng Fan <peng.fan@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>