dt-bindings: phy: inphi: fix example
commit ce7164e86a677285c25dcfe45e2b8a061f7370e1 from
https://github.com/nxp-imx/linux-imx.git

Fix the following in "make -j 8 DT_CHECKER_FLAGS=-m dt_binding_check DT_SCHEMA_FILES=phy/":

Error: Documentation/devicetree/bindings/phy/inphi,in112525.example.dts:19.9-16 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>