MA-22143-3 clk: imx95-blk-ctrl: Fix typo in imx95_blk_ctrl_match
commit 9ade2276ee41b40ea6ba594a8fe89ae46f5e4c46 from
https://github.com/nxp-imx/linux-imx.git

Fix below build error when building it as a module:
  drivers/clk/imx/imx95-blk-ctrl.c:426:25: error: use of undeclared
identifier 'imx95_blk_ctrl_match'; did you mean 'imx95_bc_of_match'?
MODULE_DEVICE_TABLE(of, imx95_blk_ctrl_match);

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Peng Fan <peng.fan@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>