dt-bindings: phy: ds125df111: fix example
commit 330b02bc83945f466f44becfafef659d80de08d6 from
https://github.com/nxp-imx/linux-imx.git

Fix the following in "make -j 8 DT_CHECKER_FLAGS=-m dt_binding_check DT_SCHEMA_FILES=phy/":

Error: Documentation/devicetree/bindings/phy/ti,ds125df111.example.dts:19.9-17 syntax error
FATAL ERROR: Unable to parse input tree

Signed-off-by: Vladimir Oltean <vladimir.oltean@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>