MA-22143-5 drm/imx: dpu95-bliteng: Import DMA_BUF namespace
commit f411e1577f356d554c03dd001873065cb0b53c4f from
https://github.com/nxp-imx/linux-imx.git

Fix below build error when building it as a module:
  ERROR: modpost: module imx95-dpu-drm uses symbol dma_buf_get
from namespace DMA_BUF, but does not import it.

Signed-off-by: Jindong Yue <jindong.yue@nxp.com>
Reviewed-by: Guangliu Ding <guangliu.ding@nxp.com>
Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>